apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/gulec2000/gitops-demo.git
    targetRevision: master
    path: .
  destination: 
    server: https://kubernetes.default.svc
    namespace: flaskapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true